# Generated by Django 3.0.5 on 2020-04-14 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vscapture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrow',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
