# Generated by Django 3.0.5 on 2020-04-14 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vscapture', '0003_auto_20200414_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrow',
            name='n2OFi',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='N2O FI'),
        ),
    ]
