# Generated by Django 3.0.5 on 2020-04-15 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vscapture', '0004_auto_20200414_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrow',
            name='aaEt',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='AA ET'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='aaFi',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='AA FI'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='aaMacSum',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='AA MAC SUM'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='agentAa',
            field=models.TextField(blank=True, choices=[('ISO', 'ISO'), ('SEV', 'SEV'), ('DES', 'DES')], null=True, verbose_name='Agent AA'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='bis',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='BIS'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='bisBsr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='BIS BSR'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='bisEmg',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='BIS EMG'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='bisSqi',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='BIS SQI'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='bsrEntropy',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='BSR Entropy'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='co2Rr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='CO2 RR'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='compliance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Compliance'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='ecgHr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ECG HR'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='eegEntropy',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='EEG Entropy'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='emgEntropy',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='EMG Entropy'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='etCo2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ET CO2'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='mvExp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='MV Exp'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='n2OEt',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='N2O ET'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='n2OFi',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='N2O FI'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='nibpDiastolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='NIBP Diastolic'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='nibpMean',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='NIBP Mean'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='nibpSystolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='NIBP Systolic'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='o2Fi',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='O2 FI'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='p1Disatolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='P1 Disatolic'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='p1Hr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='P1 HR'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='p1Mean',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='P1 Mean'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='p1Systolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='P1 Systolic'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='p2Diastolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='P2 Diastolic'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='p2Hr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='P2 HR'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='p2Mean',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='P2 Mean'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='p2Systolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='P2 Systolic'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='peep',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='PEEP'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='ppeak',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='PPeak'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='pplat',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='PPlat'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='rr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='RR'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='spo2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SpO2'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='stAvl',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ST aVL'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='stIi',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ST II'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='stV5',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ST V5'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='t1Temp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='T1 TEMP'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='t2Temp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='T2 TEMP'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='tvExp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TV Exp'),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='tvInsp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TV Insp'),
        ),
    ]
