csv_mapping = {
    "Heart Rate(/min)": "ecgHr",
    "Systolic BP(mmHg)": "nibpSystolic",
    "Diastolic BP(mmHg)": "nibpDiastolic",
    "Mean BP(mmHg)": "nibpMean",
    "SpO2(%)": "spo2",
    "ETCO2(mmHg)": "etCo2",
    "AA ET": "aaEt",
    "AA FI": "aaFi",
    "AA MAC SUM": "aaMacSum",
    "AA": "agentAa",
    "O2 FI": "o2Fi",
    "N2O FI": "n2OFi",
    "N2O ET": "n2OEt",
    "RR": "co2Rr",
    "T1": "t1Temp",
    "T2": "t2Temp",
    "P1 HR": "p1Hr",
    "P1 Sys": "p1Systolic",
    "P1 Dia": "p1Disatolic",
    "P1 Mean": "p1Mean",
    "P2 HR": "p2Hr",
    "P2 Sys": "p2Systolic",
    "P2 Dia": "p2Diastolic",
    "P2Mean": "p2Mean",
    "PPeak": "ppeak",
    "PPlat": "pplat",
    "TV Exp": "tvExp",
    "TV Insp": "tvInsp",
    "Peep": "peep",
    "MV Exp": "mvExp",
    "Compliance": "compliance",
    "RR": "rr",
    "ST II(mm)": "stIi",
    "ST V5(mm)": "stV5",
    "ST aVL(mm)": "stAvl",
    "SE": "eegEntropy",
    "RE": "emgEntropy",
    "ENTROPY BSR": "bsrEntropy",
    "BIS": "bis",
    "BIS BSR": "bisBsr",
    "BIS EMG": "bisEmg",
    "BIS SQI": "bisSqi",
}
