# Generated by Django 3.0.3 on 2020-02-21 18:43

from django.db import migrations, models
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'restaurants/data.json'
def load_data(apps, schema_editor):
    Restaurant = apps.get_model('restaurants', 'Restaurant')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Restaurant(name=name, pnt = location).save()
            except KeyError:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200221_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(load_data)
    ]
