# Generated by Django 3.0.3 on 2020-04-03 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('outline', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['id'],
            },
        ),
    ]
